[
    {
        "Id": "0",
        "Name": "Pin mặt trời công suất lớn Canadian-Solar (435W)",
        "Logo": "p-canadia435.jpg",
        "Congxuat": "435W",
        "Hang": "Canadian",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "1",
        "Name": "Pin mặt trời công suất lớn Canadian-Solar (440W)",
        "Logo": "p-canadia440.jpg",
        "Congxuat": "440W",
        "Hang": "Canadian",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "2",
        "Name": "Pin mặt trời công suất lớn Canadian-Solar (445W)",
        "Logo": "p-canadia445.jpg",
        "Congxuat": "445W",
        "Hang": "Canadian",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "3",
        "Name": "Pin mặt trời công suất lớn Canadian-Solar (450W)",
        "Logo": "p-canadia450.jpg",
        "Congxuat": "450W",
        "Hang": "Canadian",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "4",
        "Name": "Pin mặt trời công suất lớn JA-Solar (535W)",
        "Logo": "p-ja535.png",
        "Congxuat": "535W",
        "Hang": "JA-Solar",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "5",
        "Name": "Pin mặt trời công suất lớn JA-Solar (540W)",
        "Logo": "p-ja540.png",
        "Congxuat": "540W",
        "Hang": "JA-Solar",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "6",
        "Name": "Pin mặt trời công suất lớn LONGI-Solar (435W)",
        "Logo": "p-login435.jpg",
        "Congxuat": "435W",
        "Hang": "Longi-Solar",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "7",
        "Name": "Pin mặt trời công suất lớn LONGI-Solar (440W)",
        "Logo": "p-login440.jpg",
        "Congxuat": "440W",
        "Hang": "Longi-Solar",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "8",
        "Name": "Pin mặt trời công suất lớn LONGI-Solar (445W)",
        "Logo": "p-login445.jpg",
        "Congxuat": "445W",
        "Hang": "Longi-Solar",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    },
    {
        "Id": "9",
        "Name": "Pin mặt trời công suất lớn LONGI-Solar (450W)",
        "Logo": "p-login450.jpg",
        "Congxuat": "450W",
        "Hang": "Longi-Solar",

        "Loaitebaoquandien": "Mono-crystalline",
        "Soluongcell": "144 (2x(12x6))",
        "Kichthuoc": "2108 x 1048 x 40 mm",
        "Cannang": "24.7 kg",
        "Kinh": "Kính cường lực 3.2 mm",
        "Khung": "Nhôm mạ anode",
        "Hopdauday": "IP68",
        "Capdien": "4mm2",
        "Jack": "MC4-EV02",
        "Quycachdonggoi": "27 tấm / 1 kiện hàng"
    }
]